name: Black

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      task-trigger: .push

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
    - name: Run black with the --check flag
      run: |
        black --version
        black --check .
    - name: Run black and push changes
      run: |
        if [ -f ${task-trigger} ]; then
          echo "The file ${task-trigger} exists, running black without the --check flag"
          echo "Changes will be committed and pushed"
          black .
        else
          echo "The file ${task-trigger} doesn't exist, do nothing"
        fi
